
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { Rubik } from 'next/font/google';

const rubik_init = Rubik({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-rubik',
});

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">

  <body className={rubik_init.variable}>
    {children}
  </body>
</html>
  );
}
